export const GAME_CONFIG = Object.freeze({
  title: 'Evergrow',
  version: '0.6.0',
  grid: Object.freeze({ columns: 9, rows: 18 }),
  saveKey: 'evergrow.save.v1',
  mergeCount: 3,
  maxLevel: 6,
  autosaveMs: 1500,
  clarity: Object.freeze({ coreMasteryLevel: 2 }),
  tapBoost: Object.freeze({ unlockLevel: 1, threshold: 6, spawnLevel: 1 }),
  unlocks: Object.freeze({
    tapBoost: 1,
    flow: 1,
    perfect: 1,
    spark: 2,
    bloom: 2,
    resonance: 2,
    radiant: 2,
    evolution: 2,
    weather: 3,
    livingWorld: 3,
    wonders: 3,
  }),
  dayCycle: Object.freeze({ phaseLength: 7 }),
  spark: Object.freeze({ firstAt: 9, interval: 12, score: 30, spawnLevel: 1 }),
  bloom: Object.freeze({
    threshold: 150,
    turns: 5,
    spawnLevel: 1,
    mergeBaseEnergy: 12,
    mergeLevelEnergy: 5,
    perfectEnergy: 18,
    sparkEnergy: 20,
    resonanceEnergy: 7,
    radiantEnergy: 25,
    wonderEnergy: 12,
    harmonyEnergy: 16,
    wishEnergy: 18,
    festivalEnergy: 5,
  }),
  perfect: Object.freeze({ minCluster: 4, baseBonus: 20, levelBonus: 12 }),
  resonance: Object.freeze({ maxPromotionsPerTurn: 5 }),
  radiant: Object.freeze({ everyPerfectMerges: 2, mergeBonusBase: 60, mergeBonusPerLevel: 25 }),
  wonders: Object.freeze({ maxDiscoveriesPerTurn: 1 }),
  weather: Object.freeze({ firstAt: 20, clearTurns: 10, goldenMergeMultiplier: 0.5 }),
  wishes: Object.freeze({ firstAt: 12, interval: 7, settlementMinLevel: 3, festivalEvery: 2 }),
  harmony: Object.freeze({ baseReward: 140, levelReward: 70 }),
  festival: Object.freeze({ turns: 4, mergeBonus: 35 }),
});

export const ENTITY_DEFINITIONS = Object.freeze([
  { level: 0, key: 'sprout', name: 'Sprout', emoji: '🌱', score: 1, discoveryBonus: 0, stage: 'Life' },
  { level: 1, key: 'tree', name: 'Tree', emoji: '🌳', score: 5, discoveryBonus: 20, stage: 'Life' },
  { level: 2, key: 'grove', name: 'Grove', emoji: '🌲', score: 20, discoveryBonus: 60, stage: 'Nature' },
  { level: 3, key: 'village', name: 'Village', emoji: '🏠', score: 100, discoveryBonus: 200, stage: 'People' },
  { level: 4, key: 'town', name: 'Town', emoji: '🏘️', score: 500, discoveryBonus: 600, stage: 'Civilization' },
  { level: 5, key: 'city', name: 'City', emoji: '🏙️', score: 2500, discoveryBonus: 2000, stage: 'Civilization' },
  { level: 6, key: 'starport', name: 'Starport', emoji: '🚀', score: 12500, discoveryBonus: 7500, stage: 'Space' },
]);
