export const GAME_CONFIG = Object.freeze({
  title: 'Evergrow',
  version: '0.4.0',
  grid: Object.freeze({ columns: 9, rows: 18 }),
  saveKey: 'evergrow.save.v1',
  mergeCount: 3,
  maxLevel: 6,
  autosaveMs: 1500,
  spark: Object.freeze({ firstAt: 9, interval: 12, score: 30, spawnLevel: 1 }),
  bloom: Object.freeze({
    threshold: 150,
    turns: 5,
    spawnLevel: 1,
    mergeBaseEnergy: 12,
    mergeLevelEnergy: 5,
    perfectEnergy: 18,
    sparkEnergy: 20,
    resonanceEnergy: 7,
    radiantEnergy: 25,
  }),
  perfect: Object.freeze({ minCluster: 4, baseBonus: 20, levelBonus: 12 }),
  resonance: Object.freeze({ maxPromotionsPerTurn: 5 }),
  radiant: Object.freeze({ everyPerfectMerges: 2, mergeBonusBase: 60, mergeBonusPerLevel: 25 }),
  wonders: Object.freeze({ maxDiscoveriesPerTurn: 1 }),
});

export const ENTITY_DEFINITIONS = Object.freeze([
  { level: 0, key: 'sprout', name: 'Sprout', emoji: '🌱', score: 1, discoveryBonus: 0, stage: 'Life' },
  { level: 1, key: 'tree', name: 'Tree', emoji: '🌳', score: 5, discoveryBonus: 20, stage: 'Life' },
  { level: 2, key: 'grove', name: 'Grove', emoji: '🌲', score: 20, discoveryBonus: 60, stage: 'Nature' },
  { level: 3, key: 'village', name: 'Village', emoji: '🏠', score: 100, discoveryBonus: 200, stage: 'People' },
  { level: 4, key: 'town', name: 'Town', emoji: '🏘️', score: 500, discoveryBonus: 600, stage: 'Civilization' },
  { level: 5, key: 'city', name: 'City', emoji: '🏙️', score: 2500, discoveryBonus: 2000, stage: 'Civilization' },
  { level: 6, key: 'starport', name: 'Starport', emoji: '🚀', score: 12500, discoveryBonus: 7500, stage: 'Space' },
]);
