export const GOAL_DEFINITIONS = Object.freeze([
  { id: 'tree', label: 'Discover a Tree', type: 'discovery', target: 1, reward: 25 },
  { id: 'spark', label: 'Collect a Life Spark', type: 'sparks', target: 1, reward: 60 },
  { id: 'flow', label: 'Reach a 2× Flow streak', type: 'bestFlow', target: 2, reward: 100 },
  { id: 'grove', label: 'Discover a Grove', type: 'discovery', target: 2, reward: 150 },
  { id: 'perfect', label: 'Make a Perfect Merge', type: 'perfectMerges', target: 1, reward: 220 },
  { id: 'bloom', label: 'Trigger World Bloom', type: 'blooms', target: 1, reward: 300 },
  { id: 'chain', label: 'Trigger a 2× chain', type: 'bestChain', target: 2, reward: 350 },
  { id: 'village', label: 'Found a Village', type: 'discovery', target: 3, reward: 600 },
  { id: 'town', label: 'Grow a Town', type: 'discovery', target: 4, reward: 1800 },
  { id: 'city', label: 'Build a City', type: 'discovery', target: 5, reward: 6000 },
  { id: 'starport', label: 'Reach the stars', type: 'discovery', target: 6, reward: 18000 },
  { id: 'harmony', label: 'Create a Harmony district', type: 'harmonyDistricts', target: 1, reward: 900 },
  { id: 'wishes', label: 'Complete 3 settlement wishes', type: 'wishes', target: 3, reward: 1200 },
  { id: 'festival', label: 'Celebrate a Festival', type: 'festivals', target: 1, reward: 1500 },
  { id: 'weather', label: 'Experience all 3 weather moods', type: 'weatherEvents', target: 3, reward: 1800 },
]);
